server:
  port: 8101

spring:
  application:
    name: MRL-Auth
  redis:
    database: 0 # Redis数据库索引（默认为0）
    host: 127.0.0.1 # Redis服务器地址
    password: luc
    port: 6379 # Redis服务器连接端口
    timeout: 0 # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

eureka:
  instance:
    lease-renewal-interval-in-seconds: 30 # 每隔30秒向服务注册中心发送心跳
  client:
    register-with-eureka: true #注册到服务中心
    fetch-registry: true #从注册中心获取服务信息
    instance-info-replication-interval-seconds: 30 #微服务启动后30s注册到服务中心
    registry-fetch-interval-seconds: 3 #默认30，每隔30s从注册中心获取服务并缓存，此处为方便测试设置为3
    service-url:
      defaultZone: http://mrl:luc@localhost:8001/register/eureka/